---
- name: download script
  get_url:
    url: https://my-netdata.io/kickstart.sh
    dest: ~/kickstart.sh
    mode: +x
- name: run kickstart script
  command: ~/kickstart.sh --dont-wait

- name: cleanup
  file:
    path: ~/kickstart.sh
    state: absent