---
- name: install packages
  become: true
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - git
    - vim
    - curl
    - wget
    - gcc
    - linux-tools-common
    - linux-tools-generic
    - logrotate
    - etckeeper
    - tmux
    - screen
    - zsh

- shell: etckeeper vcs status
  become: true
  register: etckeeper_result
  ignore_errors: True

- name: init with etckeeper
  become: true
  shell: etckeeper init && etckeeper commit -m "first commit"
  when: etckeeper_result.rc != 0

- shell: git config --global user.email "garasubo@gmail.com"
- shell: git config --global user.name "garasubo"

- name: copy vimrc
  copy:
    src: ./files/vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    force: no

- name: add editor env var
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    create: yes
    block: |
      export EDITOR=vim
      export SUDO_EDITOR=vim
      alias sctl='systemctl'
      alias mysqld_edit='sudoedit /etc/mysql/mysql.conf.d/mysqld.cnf'
      alias mysqld_restart='sudo systemctl restart mysql'
      alias nginx_edit='sudoedit /etc/nginx/nginx.conf'
      alias nginx_restart='sudo systemctl restart nginx'


- name: copy screenrc
  copy:
    src: ./files/screenrc
    dest: "{{ ansible_env.HOME }}/.screenrc"
    force: no

- name: copy zshrc
  copy:
    src: ./files/zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    force: no

- name: copy tmux.conf
  copy:
    src: ./files/tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    force: no

- name: chsh to zsh
  become: true
  user:
    name: isucon
    shell: /bin/zsh
