---

- name: install basic element
  hosts: all
  user: isucon
  become: yes
  tasks:
  - name: install packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - git
      - vim
      - curl
      - net-tools
      - wget
      - gcc
      - keepalived
      - epel-release
  - name: install from epel
    yum:
      name: "{{ packages }}"
      enablerepo: epel
      state: latest
    vars:
      packages:
      - etckeeper
      - redis

  - shell: etckeeper vcs status
    register: etckeeper_result
    ignore_errors: True
  - name: init with etckeeper
    shell: etckeeper init && etckeeper commit -m "first commit"
    when: etckeeper_result.rc != 0

  - name: install netdata
    shell: bash <(curl -Ssf https://my-netdata.io/kickstart-static64.sh) --dont-wait --dont-start-it
    args:
      executable: /bin/bash

