---
- name: install basic element
  hosts: all
  become: yes
  tasks:
  - name: remove old docker
    yum:
      name: "{{ packages }}"
      state: absent
    ignore_errors: True
    vars:
      packages:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
  - name: prepare
    yum:
        name: "{{ packages }}"
    vars:
        packages:
            - yum-utils
            - device-mapper-persistent-data
            - lvm2
  - name: register docker ce
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - name: install docker ce
    yum:
        name: docker-ce
        state: latest

